### ISSUE TITLE
having sketch input only

### ISSUE THREAD

**Issue by HadeerArafa** [Nithin-GK/UniteandConquer#2]
I want to raise this issue because I wanted to ask if we can only enter a sketch image as our input because this case gives an error and I fixed it, so if we think it's a problem I will be more than happy to commit but if you think it's not an error and we should not just input a sketch image then sorry for this mistake

**Comment by Nithin-GK** [comment]
Hello,

Thank you for getting back regarding this. Our model should be able to take in just a sketch as input.  I will check for the error. I would also appreciate it if you could commit to the fix.
