### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by floppycracken** [Nithin-GK/UniteandConquer#4]
Hello,
Are you planning to release the instructions for training code?
Thank you

**Comment by Nithin-GK** [comment]
Hello,

I will upload the training code shortly.

**Comment by MMarvasti** [comment]
Any updates?

**Comment by Jiawei804** [comment]
I'm also looking forward to this update。

**Comment by Nithin-GK** [comment]
Hello,

I have updated the training code for semantic maps and text. For generic images, off the shelf models were used the download links are provided in https://github.com/Nithin-GK/UniteandConquer/blob/main/utils/download_models.py
