### ISSUE TITLE
How to create our own face and hair map?

### ISSUE THREAD

**Issue by Open-Debin** [Nithin-GK/UniteandConquer#5]
Dear author, thank you for your codes very much. The facial segmentation mask is from the CelebA-HQ-Mask dataset. But you only provide part of the data. Could you please provide the codes that make the face and hair map?

**Comment by Nithin-GK** [comment]
Hello, I created the Hair and Face Masks using FARL face parser. https://github.com/FacePerceiver/FaRL. I will update my implementation shortly
